
Vagrant.configure("2") do |config|
  config.vm.box = "ansible/tower"
  config.vm.network "forwarded_port", guest: 443, host: 8080, host_ip: "127.0.0.1"
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
