#PUPPET Setup
#This will take 30 mins of run time, depending your machine capacity.

BOX_IMAGE = "bento/centos-7.2"
NODE_COUNT = 2
Vagrant.configure("2") do |config|
  (1..NODE_COUNT).each do |i|
    config.vm.define "puppet-node#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "node#{i}"
      subconfig.vm.network :private_network, ip: "10.0.1.#{i + 10}"
    end
    config.vm.provision "shell" do |shell|
      shell.name = "Script for base setup on agent"
      shell.path = "https://gist.githubusercontent.com/bikranz4u/f50d9ed5ff4f58e891bef05e0c5e56a1/raw/cc5278bb849fd986bb0d4e012a1139a180880819/epel-ruby-setup.sh"
    end
    config.vm.provision "shell" do |shell|
      shell.name = "ScriptFor-puppet-agent-installation"
      shell.path = "https://gist.githubusercontent.com/bikranz4u/ec0d0d1561d1fc403c78820e5452dbf9/raw/4b61eb4d1adfd7406edeca2733edd44e89f89976/puppet-agent-install.sh"
    end
  end
  config.vm.define "Puppet-Master" do |subconfig|
    subconfig.vm.hostname = "Puppet-Master"
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.network "private_network", ip: "10.0.1.10"
    #subconfig.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
    #subconfig.vm.synced_folder "./ansible-config-files", "/home/vagrant/ansible-setup/"
    subconfig.vm.provision "shell" do |shell|
      shell.name = "Script for base setup on master"
      shell.path = "https://gist.githubusercontent.com/bikranz4u/f50d9ed5ff4f58e891bef05e0c5e56a1/raw/cc5278bb849fd986bb0d4e012a1139a180880819/epel-ruby-setup.sh"
    end  
    subconfig.vm.provision "shell" do |shell|
      shell.name = "puppet-master-installation"
      shell.path = "https://gist.githubusercontent.com/bikranz4u/aac50c2828370ae4c8e8f48a6a159543/raw/d5c5051379b058870aba4ca6e9731a70db6ddcc6/puppet-master-installation.sh"
    end
  end
end
