#https://manski.net/2016/09/vagrant-multi-machine-tutorial/
Vagrant.configure("2") do |config|
  config.vm.define "Ansible-Master" do |subconfig|
    subconfig.vm.hostname = "Ansible-Master"
    subconfig.vm.box = "bento/ubuntu-20.04"
    subconfig.vm.network "private_network", ip: "192.168.56.5"
    #subconfig.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  end
  config.vm.define "Ansible-node-1" do |subconfig|
    subconfig.vm.hostname = "Ansible-node-1"
    subconfig.vm.box = "bento/ubuntu-20.04"
    subconfig.vm.network "private_network", ip: "192.168.56.6"
    #subconfig.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  end
  config.vm.define "Ansible-node-2" do |subconfig|
    subconfig.vm.hostname = "Ansible-node-2"
    subconfig.vm.box = "bento/ubuntu-20.04"
    subconfig.vm.network "private_network", ip: "192.168.56.7"
    #subconfig.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  end
end
