Vagrant.configure(2) do |config|
	config.vm.define "devops-box" do |devbox|
		devbox.vm.box = "centos/7"
    		devbox.vm.network "private_network", ip: "192.168.56.111"
    		devbox.vm.hostname = "devops-centos7"
      		devbox.vm.provision "shell", path: "devops-box-setup.bash"
    		devbox.vm.provider "virtualbox" do |v|
    		  v.memory = 4096
    		  v.cpus = 2
    		end
	end
end
