
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  # config.vm.network "private_network", ip: "192.168.33.10"
  #config.vm.network "private_network", type: "dhcp"
  config.vm.network "private_network", ip: "192.168.1.26"

  # config.vm.network "public_network"
  #
  config.vm.provider "virtualbox" do |vb|

     vb.gui = false
  
  #   # Customize the amount of memory on the VM:
     vb.memory = "1024"
   end

  config.vm.provision "shell", inline: <<-SHELL
     apt-get update -y
     apt-get install apache2 -y 
   SHELL
end


# By Using eth1 IP the web site can be accessed, ifconfig will do.
