# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  #This will be the name of the VM  used by vagrant for standard out and log
  config.vm.define "web-server"
  
  #Hostname of the Guest VM
  config.vm.hostname = "web-server"

  #VM image to be used
  config.vm.box = "bento/ubuntu-16.04"

  #Port mapping 
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  #Local host directory mapping with VM
  config.vm.synced_folder "/Users/bikrdas/Desktop/DevOps/Vagrant/vagrant/single-VM/", "/var/www/html/"

  # Provider-specific configuration so you can fine-tune various
  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
     vb.gui = false
  #   # Customize the amount of memory on the VM:
     vb.memory = "1024"
  end
  # Enable provisioning with a shell script. 
  config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     #apt-get install -y apache2
  SHELL
  config.vm.provision "shell", run: "always", inline: <<-SHELL
     echo "Heloo"
  SHELL
end
