BOX_IMAGE = "bento/centos-7.2"
Vagrant.configure("2") do |subconfig|
    subconfig.vm.define "Jenkins-Master"
    subconfig.vm.hostname = "Jenkins-Master"
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.network "private_network", ip: "10.0.0.10"
    subconfig.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "127.0.0.1"
    subconfig.vm.provision  "shell" do |shell|
      shell.path = "https://gist.githubusercontent.com/bikranz4u/2feab7ecdfca1fb4fdd5c4fc56696dfa/raw/6ecf12c42437d84d458f80251df18b8875a31547/Java-jenkins-Installation.sh"
    #subconfig.vm.synced_folder "./ansible-config-files", "/home/vagrant/ansible-setup/"
    end
end

# If face issue related to jenkin start ..then modify the java path in /etc/rc.d/init.d/jenkins
